###############################################################################
#####################     FICHIER PARAMETRES DEVOPS PROD  #####################
###############################################################################
# VG / LV Config
vg_name_1: 'vg-data'
lv_name_1: 'data'
mount_name_1: '/mnt/data'

vg_name_2: 'vg-vtom'
lv_name_2: 'vtom'
mount_name_2: '/mnt/vtom'

# docker var
user: vtom
user_comment: 'Admin Visual TOM'
user_id: 1501
group_name: vtom
group_id: 1501
password_user: Vt0m23!

# Open port
plage_port_vtom: "30001:30100"

# Vmware custom attributes
custom_1_name: "Contact metier"
custom_1_value: "adm-vtom@cprpsncf.fr"
custom_2_name: "Plage de maintenance"
custom_2_value: "24/24h"

# repertoire
folder_vtom_bases: '/mnt/data/vtom/bases'
folder_vtom_logs: '/mnt/data/vtom/logs'
folder_vtom_trace: '/mnt/data/vtom/traces'
folder_vtom_backup: '/mnt/vtom/backup'

folder_datas: '/datas'
folder_logs: '/datas/logs'
folder_sas_ansible : '/datas/Sas_Ansible'
folder_sas_archive : '/datas/Sas_Archive'

folder_sas_Application : '/datas/Sas_Livrables/Sas_Application'
folder_sas_Lib : '/datas/Sas_Livrables/Sas_Lib'
folder_sas_Properties : '/datas/Sas_Livrables/Sas_Properties'
folder_sas_RessourceAdapter : '/datas/Sas_Livrables/Sas_RessourceAdapter'
folder_sas_ShareLib : '/datas/Sas_Livrables/Sas_ShareLib'

# Stockage local des livrables
folder_local_app : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/app"
folder_local_data : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/data"
folder_local_lib : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/lib"
folder_local_properties : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/properties"
folder_local_properties_sa : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/properties_sa"
folder_local_ressourceadapter : "/datas/Livrables/{{ typesa_app_var[-3:] }}/{{ env_var }}/ressourceadapter"

# Env extrat
env_working : "{{ name_host[:-3] }}"

# Network
name_host : "{{ inventory_hostname.split('.')[0] }}"
# VLAN
