# Creation vm weblogic

- name: creation vm weblogic 12.2.1.3.0
  hosts: weblogicadmin
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
     - vars_SA_ALL.yaml
     
  roles:
     - linux 
     - jdk
     - weblogic_122130_only	
     - patch_122130_only

