# Creation vm weblogic

- name: creation vm weblogic 12.2.1.3.0
  hosts: weblogicadmin
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo

  vars_files:
     - vars_ansible.yaml

  roles:
     - linux 
     - jdk
     - weblogic_122130_only
     - soa_122130
     - osb_122130
     - patch_122130

