
# Maj password 

- name: Password rollover
  hosts: '{{ df }}'
  gather_facts: false
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo


  roles:
      - password_rollover
  