###############################################################################
#####################     FICHIER PARAMETRES DEVOPS PROD  #####################
###############################################################################
# VG / LV Config
vg_name_1: 'vg-misc'
lv_name_1: 'data'
lv_size_1: '50g'
mount_name_1: '/data'

lv_name_2: 'commun'
lv_size_2: '50g'
mount_name_2: '/espace_commun'

# Hraccess var
user1: gitlab-runner
user1_comment: 'User gitlab-runner'
user1_id: 1501
group1_name: hr
group1_id: 1000
user1_password: gitlab

# Vmware custom attributes
custom_1_name: "Contact metier"
custom_1_value: "tot@cprpf.fr"
custom_2_name: "Plage de maintenance"
custom_2_value: "12/24h"

# Tags attributes
tag_app: "DVS"
tag_env: "PROD"
tag_midd: "AN"

# repertoire
folder_datas: '/datas'
folder_logs: '/datas/logs'
folder_sas_ansible : '/datas/Sas_Ansible'
folder_sas_archive : '/datas/Sas_Archive'

folder_sas_Application : '/datas/Sas_Livrables/Sas_Application'
folder_sas_Lib : '/datas/Sas_Livrables/Sas_Lib'
folder_sas_Properties : '/datas/Sas_Livrables/Sas_Properties'
folder_sas_RessourceAdapter : '/datas/Sas_Livrables/Sas_RessourceAdapter'
folder_sas_ShareLib : '/datas/Sas_Livrables/Sas_ShareLib'

# Env extrat
env_working : "{{ name_host[:-3] }}"

# Network
name_host : "{{ inventory_hostname.split('.')[0] }}"

# VLAN
