# Installation weblogic 12.1.3.0.0

- name: copie fichier response files weblogic sur vms cible
  template:
    src: install-wls121300.j2
    dest: "{{ folder_install }}/install-wls121300.rsp"
    owner: "{{ user_oracle }}"
    group: "{{ group_oracle }}"

- name: Test existence installateur weblo 
  stat:
    path: "{{ folder_install }}/{{ version_weblogic }}"
  register: installWL_found

- name: Copie installeur weblo
  copy:
   src: "{{ version_weblogic }}"
   dest: "{{ folder_install }}"
   owner: "{{ user_oracle }}"
   group: "{{ group_oracle }}"
  when: not installWL_found.stat.exists

- name: creation repertoire OraInventory
  file: state=directory path="{{ folder_oracle }}/oraInventory" owner="{{ user_oracle }}" group="{{ group_oracle }}" mode=755

- name: /etc/oraInst.loc
  copy:
    content="inventory_loc={{ folder_oracle }}/oraInventory\n\rinst_group={{ group_oracle }}\n\r"
    dest=/etc/oraInst.loc
    mode="u=rw,g=r,o=r"

- name: Test existence installation weblo
  stat:
    path: "{{ folder_middleware_home }}"
  register: WL_found

- name: Installation weblogic  
  command: "{{ folder_oracle }}/{{ version_jdk_short }}/bin/java -Xms1024m -Xmx1024m -Djava.io.tmpdir={{ folder_tmp }} -debug -jar {{ folder_install }}/{{ version_weblogic }} -silent -novalidation -responseFile {{ folder_install }}/install-wls121300.rsp -invPtrLoc /etc/oraInst.loc"
  become: yes
  become_user: '{{ user_oracle }}'
  when: not WL_found.stat.exists