---
# #########################################################################
# #####################  FICHIER PARAMETRES           #####################
# #########################################################################

########################## VAR BPU ##########################
# Application attributes de BPU
tag: "BPU"
name: "BPU"
domaine: "DSIO-RA"
composant: "Oracle Java,Oracle Service bus 11g,Oracle Database 12c"
techno: "Oracle Java,Oracle Service bus 11g,Oracle Database 12c"
desc: "BPU signifie Base des populations unifiée et l'application BPU a pour vocation de constituer un référentiel des populations gérées par la CPR partageable par tous les systèmes d'information"
