###############################################################################
#####################  CUSTOM VM DOCKER                  #####################
###############################################################################

- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present

- name: Include task Add VG/LV create if vg not exists
  include_role:
    name: vm_sidr_customization
    tasks_from: add_vg_lv.yaml

- name: group "exploit" create
  group:
    name: "{{ group_1_name }}"
    gid: "{{ group_1_id }}"
    state: present

- name: group "oinstall" create
  group:
    name: "{{ group_2_name }}"
    gid: "{{ group_2_id }}"
    state: present

- name: group "dba" create
  group:
    name: "{{ group_3_name }}"
    gid: "{{ group_3_id }}"
    state: present

- name: Adding user expldu
  user:
    name: "{{ user_1 }}"
    comment: "{{ user_1_comment }}"
    group: "{{ group_1_name }}"
    uid: "{{ user_1_id }}"
    shell: /bin/bash
    append: true

- name: change password
  user:
    name: "{{ user_1 }}"
    state: present
    password: "{{ user_1_password | password_hash('sha512') }}"

- name: Adding user oracle
  user:
    name: "{{ user_2 }}"
    comment: "{{ user_2_comment }}"
    group: "{{ group_2_name }}"
    uid: "{{ user_2_id }}"
    shell: /bin/bash
    append: true

- name: change password
  user:
    name: "{{ user_2 }}"
    state: present
    password: "{{ user_2_password | password_hash('sha512') }}"

- name: adding user oracle to group dba
  user:
    name: "{{ user_2 }}"
    groups: "{{ group_3_name }}"
    append: true

- name: Copie conf sudo 
  copy: 
    src: "{{ item  }}"
    dest: "/etc/sudoers.d/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ansible
  tags: 
    - Cp_sudoers

- name: Copy bash rc
  copy:
    src: "bash.bashrc"
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Copy bash rc oracle
  copy:
    src: "bashoracle.bashrc"
    dest: /home/oracle/.bashrc
    owner: oracle
    group: oinstall
    mode: 0644
    backup: true

- name: Include Tools
  include_role:
    name: vm_sidr_customization
    tasks_from: tools.yaml
  tags: 
    - katello_install