###############################################################################
#####################  Param systemd admin WL             #####################
###############################################################################

# Configuration systemd

- name: copie du template weblogic vers VM
  template:
    src: weblogic.j2
    dest: "/etc/systemd/system/weblogic.service"
    owner: "root"
    group: "root"
    mode: 0755

- name: Activation du service
  systemd:
    name: weblogic.service
    state: started
    enabled: yes
    daemon_reload: yes
