- name: Add tags to a virtual machine
  community.vmware.vmware_tag_manager:
    hostname: '{{ vmware_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_pass }}'
    validate_certs: no
    tag_names:
      - tag: {{ application }}
        category: Applications
      - tag: {{ environnement }}
        category: Environnement
      - tag: {{ middleware }}
        category: Middleware     
    object_name: "{{ inventory_hostname_short }}"
    object_type: VirtualMachine
    state: add
  register: tag_add
  tag: tag

- name: Debug attri
  debug: 
    msg: "{{ tag_add }}"