###############################################################################
#####################  CUSTOM VM DOCKER                  #####################
###############################################################################
- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present

- name: Format partition
  filesystem:
    fstype: ext4
    dev: /dev/sdb1

- name: create partition
  parted:
    device: /dev/sdc
    number: 1
    flags: [ lvm ]
    state: present

- name: Format partition
  filesystem:
    fstype: ext4
    dev: /dev/sdc1

- name: group "edit create
  group:
    name: "{{ group_1 }}"
    state: present
  tags: 
    - adduser  

- name: Adding user edit  
  user: 
    name: "{{ user_1 }}"
    group: "{{ group_1 }}"
    shell: /bin/bash
    append: yes
  tags: 
    - adduser

- name: change password
  user:
    name: "{{ user_1 }}"
    state: present
    password: "{{ password_user_1 | password_hash('sha512') }}"
  tags: 
    - adduser

- name: group "exploit" create
  group:
    name: "{{ group_2 }}"
    state: present
  tags: 
    - adduser

- name: change password
  user:
    name: "{{ user_2 }}"
    state: present
    password: "{{ password_user_2 | password_hash('sha512') }}"
  tags: 
    - adduser

- name: Include task Add VG/LV create if vg not exists
  include_role:
    name: vm_ksl_customization
    tasks_from: add_vg_lv.yaml
  tags:
      - symbolink

- name: Include task modify network
  include_role:
    name: vm_ksl_customization
    tasks_from: modify_network.yaml
  tags: 
      - modify_netw

- name: Include Tools
  include_role:
    name: vm_ksl_customization
    tasks_from: tools.yaml
  tags:
    - tools_bash

- name: Include Deploy Cron
  include_role:
    name: vm_ksl_customization
    tasks_from: cron_deploy.yaml
  tags:
    - cron

- name: Install tomcat
  include_role: 
    name: vm_ksl_customization
    tasks_from: install_tomcat.yaml
  when: tomcat_state == "present"
  tags:
    - install_java
    
- name: configure tomcat
  include_role: 
    name: vm_ksl_customization
    tasks_from: configure_tomcat.yaml
  when: tomcat_state == "present"
  tags:
      - config_tomcat

- name: Uninstall tomcat
  include_role: 
    name: vm_ksl_customization
    tasks_from: uninstall_tomcat.yaml
  when: tomcat_state == "absent"

- name: Install Instant client Oracle
  include_role: 
    name: vm_ksl_customization
    tasks_from: install_instantclient_oracle.yaml
  tags:
    - client_oracle

