- name: Check Vg data exist
  shell: 'lsblk | grep "vg--data"'
  register: result-vgdata
  ignore_errors: true

- debug:
    var: ansible_lvm

- name: Debug lvm
  debug: 
    var: "result-vgdata.rc"

- name: Create a volume group on
  lvg:
    vg: "{{ vg_name_1 }}"
    pvs: /dev/sdb1
    state: present
  ignore_errors: True
  failed_when: false
  no_log: True

- name: Create a logical volume 
  lvol:
    vg: "{{ vg_name_1 }}"
    lv: "{{ lv_name_1 }}"
    size: 100%FREE
    state: present
  ignore_errors: true
  failed_when: false
  no_log: true
  
- name: Creafe File System
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vg_name_1 }}/{{ lv_name_1 }}"
    
- name: Create a directory if it does not exist
  file:
    path: "/{{ mount_name_1 }}"
    state: directory
    mode: '0755'

- name: Mount Logical volume FS
  mount:
    name: "/{{ mount_name_1 }}"
    src: "/dev/{{ vg_name_1 }}/{{ lv_name_1 }}"
    fstype: ext4
    state: mounted

- name: Check Vg vtom exist
  shell: 'lsblk | grep "vg--vtom"'
  register: result-vgvtom
  ignore_errors: true

- debug:
    var: ansible_lvm

- name: Debug lvm
  debug: 
    var: "result-vgvtom.rc"

- name: Create a volume group on
  lvg:
    vg: "{{ vg_name_2 }}"
    pvs: /dev/sdc1
    state: present
  ignore_errors: True
  failed_when: false
  no_log: True

- name: Create a logical volume 
  lvol:
    vg: "{{ vg_name_2 }}"
    lv: "{{ lv_name_2 }}"
    size: 100%FREE
    state: present
  ignore_errors: true
  failed_when: false
  no_log: true
  
- name: Creafe File System
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vg_name_2 }}/{{ lv_name_2 }}"
    
- name: Create a directory if it does not exist
  file:
    path: "/{{ mount_name_2 }}"
    state: directory
    mode: '0755'

- name: Mount Logical volume FS
  mount:
    name: "/{{ mount_name_2 }}"
    src: "/dev/{{ vg_name_2 }}/{{ lv_name_2 }}"
    fstype: ext4
    state: mounted
