- name: Check Vg Misc exist
  shell: 'lsblk | grep "vg--misc"'
  register: result
  ignore_errors: true

- name: Debug lvm
  debug: 
    var: "result.rc"

- name: Create a volume group on Misc
  lvg:
    vg: "{{ vg_name_1 }}"
    pvs: /dev/sdb1
    state: present
  ignore_errors: True
  failed_when: false
  no_log: True

- name: Create a logical volume {{ lv_name_1 }}
  lvol:
    vg: "{{ vg_name_1 }}"
    lv: "{{ lv_name_1 }}"
    size: "{{ lv_size_1 }}"
    state: present
  ignore_errors: true
  failed_when: false
  no_log: true
  
- name: Create File System {{ lv_name_1 }}
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vg_name_1 }}/{{ lv_name_1 }}"
    
- name: Create a directory if it does not exist
  file:
    path: "/{{ mount_name_1 }}"
    state: directory
    mode: '0755'

- name: Mount Logical volume FS {{ lv_name_1 }}
  mount:
    name: "/{{ mount_name_1 }}"
    src: "/dev/{{ vg_name_1 }}/{{ lv_name_1 }}"
    fstype: ext4
    state: mounted

- name: Create a logical volume {{ lv_name_2 }}
  lvol:
    vg: "{{ vg_name_1 }}"
    lv: "{{ lv_name_2 }}"
    size: "{{ lv_size_2 }}"
    state: present
  ignore_errors: true
  failed_when: false
  no_log: true
  
- name: Create File System {{ lv_name_2 }}
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vg_name_1 }}/{{ lv_name_2 }}"
    
- name: Create a directory if it does not exist
  file:
    path: "/{{ mount_name_2 }}"
    state: directory
    mode: '0755'

- name: Mount Logical volume FS {{ lv_name_2 }}
  mount:
    name: "/{{ mount_name_2 }}"
    src: "/dev/{{ vg_name_1 }}/{{ lv_name_2 }}"
    fstype: ext4
    state: mounted